//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mnemonika.AppModules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auxi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auxi()
        {
            this.Mnemonic = new HashSet<Mnemonic>();
            this.Word = new HashSet<Word>();
        }
    
        public int IdAux { get; set; }
        public string RusWord { get; set; }
        public string EngWord { get; set; }
        public string TipicalMistake { get; set; }
        public string BritishTrans { get; set; }
        public string NorthAmericanTrans { get; set; }
        public string Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mnemonic> Mnemonic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Word> Word { get; set; }
    }
}
