//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mnemonika.AppModules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mnemonic
    {
        public int IdMnemonic { get; set; }
        public int AuxId { get; set; }
        public string MnemonicDevice { get; set; }
    
        public virtual Auxi Auxi { get; set; }
    }
}
