//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mnemonika.AppModules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Word
    {
        public int IdWord { get; set; }
        public int PartOfSpeechId { get; set; }
        public int ThemeId { get; set; }
        public Nullable<System.DateTime> StudyDate { get; set; }
        public int AuxId { get; set; }
        public Nullable<int> DifficultyId { get; set; }
        public int UserId { get; set; }
        public string Example { get; set; }
        public string Hint { get; set; }
        public bool BasicExampleMark { get; set; }
        public bool GeneralCardMark { get; set; }
    
        public virtual Auxi Auxi { get; set; }
        public virtual Difficulty Difficulty { get; set; }
        public virtual PartOfSpeech PartOfSpeech { get; set; }
        public virtual Theme Theme { get; set; }
        public virtual User User { get; set; }
    }
}
